/*
 * generated by Xtext
 */
package com.dexels.navajo.dsl.tsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TslUiModule extends com.dexels.navajo.dsl.tsl.ui.AbstractTslUiModule {
	public TslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
