/*
 * generated by Xtext
 */
package com.dexels.navajo.dsl.tsl;

import com.dexels.navajo.dsl.tsl.validation.TslJavaValidator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TslRuntimeModule extends com.dexels.navajo.dsl.tsl.AbstractTslRuntimeModule {

	
	@Override
	public Class<? extends TslJavaValidator> bindTslJavaValidator() {
		System.err.println("Binding TSL ");
		return super.bindTslJavaValidator();
	}

	
}
