./cvsgit.sh sportlink-adapters com.sportlink.adapters
./cvsgit.sh sportlink-analysis com.sportlink.analysis
./cvsgit.sh sportlink-clnt-v2 com.sportlink.client
./cvsgit.sh sportlink-dba com.sportlink.dba
./cvsgit.sh sportlink-downloadcentre com.sportlink.downloadservlet
./cvsgit.sh sportlink-dwf-bv com.sportlink.dwf.bv.web
./cvsgit.sh sportlink-knvb-digitaalinschrijven com.sportlink.digitaalinschrijven
./cvsgit.sh sportlink-serv com.sportlink.serv
./cvsgit.sh sportlink-serv-AAA com.sportlink.aaa
./cvsgit.sh sportlink-serv-comp com.sportlink.comp
./cvsgit.sh sportlink-serv-crystal com.sportlink.crystal
./cvsgit.sh AccommodatieZaken com.sportlink.accommodatiezaken
./cvsgit.sh AutomatischePouleIndeling com.sportlink.optimizepool
./cvsgit.sh DWFDashboard com.sportlink.dwf.dashboard
./cvsgit.sh DexDMS com.sportlink.dms.joomla
./cvsgit.sh DocumentManagement com.sportlink.dms.client
./cvsgit.sh GoogleEarthAccommodations com.sportlink.accommodations
# needs trimming down
#./cvsgit.sh KNHB-Sporttaal com.sportlink.knhb.sporttaal
./cvsgit.sh KNVBWidget com.sportlink.knvb.widget
./cvsgit.sh KNZB-JSP-Interface com.sportlink.knzb.interface
./cvsgit.sh MDex com.sportlink.james
./cvsgit.sh NavajoSwingClient com.sportlink.swing.client
./cvsgit.sh NevoboDPS com.sportlink.nevobo.dps
./cvsgit.sh SportlinkBackoffice com.sportlink.backoffice
./cvsgit.sh SportlinkCIF com.sportlink.cif
./cvsgit.sh SportlinkClub com.sportlink.club
./cvsgit.sh SportlinkDWF com.sportlink.dwf.av
./cvsgit.sh SportlinkDashboard com.sportlink.dashboard
./cvsgit.sh SportlinkDwfTouch com.sportlink.dwf.bv.ios
./cvsgit.sh SportlinkMatchForms com.sportlink.matchforms
./cvsgit.sh SportlinkOfficialPortal com.sportlink.officialportal
./cvsgit.sh SportlinkReports com.sportlink.reports
./cvsgit.sh SportlinkTeamRegistration com.sportlink.teamregistration
./cvsgit.sh SportlinkWebshop com.sportlink.webshop
./cvsgit.sh TensingOracle com.sportlink.tensing
./cvsgit.sh TipiFacilityOccpation com.sportlink.tipi.facilityoccupation
./cvsgit.sh GeoJsp com.sportlink.geo.jsp
