version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}
            - v1-dependencies-

      - run: |
          cd setup/com.dexels.target
          mvn -s ../../.circleci/conf/settings.xml install 
          cd ../..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}

      # run tests
      - run: mvn -s .circleci/conf/settings.xml deploy -Denvironment=release
      - run: |
          cd ~
          du -hs .m2
          zip -r navajo_maven.zip .m2
      - store_artifacts:
          path: ~/navajo_maven.zip
          destination: navajo_maven.zip
      - store_artifacts:
          path: ~/repo/setup/com.dexels.p2/target/com.dexels.p2-1.0.0-SNAPSHOT.zip
          destination: navajo_p2.zip
      - run: |
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"newmaven"}' "https://circleci.com/api/v1.1/project/github/dexels/enterprise/build?circle-token=${CIRCLE_TOKEN}
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"newbuild"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-platform/build?circle-token=${CIRCLE_TOKEN}
