version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
#      - run: |
#          git clone git@github.com:Dexels/enterprise.git
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}
            - v1-dependencies-

      - run: |
          cd setup/com.dexels.target
          mvn install
          cd ../..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}

      # run tests!
      - run: mvn install
      - run: |
          cd ~
          du -hs .m2
          zip -r navajo_maven.zip .m2
      - store_artifacts:
          path: ~/navajo_maven.zip
          destination: navajo_maven.zip
