version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx2000m
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}
          - v1-dependencies-

      - run: |
                cd setup/com.dexels.target
                mvn install
                cd ../..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "setup/com.dexels.target/repo.dexels.com.target" }}
        
      # run tests!
      - run: mvn install

