version: 2
jobs:
  build:
    branches:
      only:
        newmaven
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup/com.dexels.target/maven.target" }}
      - run: |
          cd setup/com.dexels.target
          mvn -s ../../.circleci/conf/settings.xml -B install 
          cd ../..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "setup/com.dexels.target/maven.target" }}

      # run tests
      - run: mvn -B -s .circleci/conf/settings.xml -T 1.5C deploy -Denvironment=release
      - run: |
          cd ~
          du -hs .m2
          zip -r navajo_maven.zip .m2
      - store_artifacts:
          path: ~/navajo_maven.zip
          destination: navajo_maven.zip
      - store_artifacts:
          path: ~/repo/setup/com.dexels.p2/target/com.dexels.p2-1.0.0-SNAPSHOT.zip
          destination: navajo_p2.zip
      - store_artifacts:
          path: ~/repo/setup/com.dexels.vaadin.p2/target/com.dexels.vaadin.p2-1.0.0-SNAPSHOT.zip
          destination: vaadin_p2.zip
      - store_artifacts:
          path: ~/repo/setup/com.dexels.streams.p2/target/com.dexels.streams.p2-1.0.0-SNAPSHOT.zip
          destination: streams_p2.zip
      - run: |
          ssh -o StrictHostKeyChecking=no navajo@repo.dexels.com "mkdir -p /var/www/html/repo/eclipse/navajo_${MINORTAG}.${CIRCLE_BUILD_NUM}/"
          scp -r ~/repo/setup/com.dexels.p2/target/repository/* navajo@repo.dexels.com:/var/www/html/repo/eclipse/navajo_${MINORTAG}.${CIRCLE_BUILD_NUM}
      - run: |
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"newmaven"}' "https://circleci.com/api/v1.1/project/github/dexels/enterprise/build?circle-token=${CIRCLE_TOKEN}"
          #curl -X POST --header "Content-Type: application/json" -d '{"branch":"newbuild"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-platform/build?circle-token=${CIRCLE_TOKEN}"
