package com.dexels.config.runtime;

public enum TestConfig {
	NAVAJO_TEST_USER,
	NAVAJO_TEST_PASS,
	NAVAJO_TEST_SERVER,
	NAVAJO_TEST_LOCAL,
	NAVAJO_TEST_REACTIVE,
	NAVAJO_TEST_LOCALREACTIVE,
	KAFKA_DEVELOP,
	KAFKA_TEST,
	ORACLE_DUMMY_URL,
	MONGO_DEV_JUNIT,
	MONGO_TEST_AAA,
	MONGO_TEST_EXTERNALSTORE,
	MONGO_TEST_REPLICATE,
	MONGO_TEST_SPORTLINK,
	MONGO_PROD_AAA,
	MONGO_PROD_EXTERNALSTORE,
	MONGO_PROD_REPLICATE,
	MONGO_PROD_SPORTLINK,
	HTTP_TEST_URL,
	HTTP_TEST_TOKEN,
	HTTP_TEST_BUCKET,
	HTTP_TEST_SECRET,
	ELASTICSEARCH_SERVER,
	ELASTICSEARCH_INDEX,
	ELASTICSEARCH_TYPE;
	
	
	
    public String getValue() {
        return System.getenv(this.toString());
    }
}
