DROP TABLE NAVAJOACCESS
/

CREATE TABLE NAVAJOACCESS (
ACCESS_ID 	VARCHAR2(128) NOT NULL,
WEBSERVICE 	VARCHAR2(128) NOT NULL,
USERNAME 	VARCHAR2(128),
THREADCOUNT 	NUMBER,
TOTALTIME 	NUMBER,
PARSETIME 	NUMBER,
AUTHORISATIONTIME NUMBER,
REQUESTSIZE 	NUMBER,
REQUESTENCODING VARCHAR2(64),
COMPRESSEDRECV 	CHAR(1),
COMPRESSEDSND 	CHAR(1),
IP_ADDRESS 	VARCHAR2(32),
HOSTNAME 	VARCHAR2(128),
CREATED 	TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
	CONSTRAINT NAVAJOACCESS_PK primary key (ACCESS_ID) 
		using index
)
/

DROP TABLE NAVAJOLOG
/

CREATE TABLE NAVAJOLOG (
ACCESS_ID 	VARCHAR2(128) NOT NULL, 
EXCEPTION 	VARCHAR2(4000), 
NAVAJOIN 	BLOB, 
NAVAJOOUT 	BLOB,
   CONSTRAINT NAVAJOLOG_PK primary key (ACCESS_ID)
                using index
)
/

CREATE INDEX navajoaccess_indx ON navajoaccess (
  username,
  webservice
)
/

QUIT
