DROP TABLE STATISTICS
/

CREATE
    TABLE STATISTICS
    (
        MODULE VARCHAR2(32) NOT NULL,
        VALUE VARCHAR2(32) NOT NULL,
        WEEK NUMBER(2) NOT NULL,
        YEAR NUMBER(4) NOT NULL,
        TIMESTMP TIMESTAMP(6)
WITH
    TIME ZONE,
    SERVER VARCHAR2(128)
    )
/

CREATE INDEX STATISTICS_MODL_SRV_TIME ON statistics
(
  MODULE, SERVER, TIMESTMP
)
/

QUIT
