/* Generated By:JJTree: Do not edit this line. ASTNullNode.java */

package com.dexels.navajo.parser;

public class ASTNullNode extends SimpleNode {

  public ASTNullNode(int id) {
    super(id);
  }

  public Object interpret() {
    return null;
  }

}
