#!/bin/sh
#
# Launch JavaCC from bash on Windows
#
# Copyright (C) 1998-2000 Metamata, Inc.

export CLASSPATH=/home/arjen/projecten/Navajo/lib/javacc.jar
#export CLASSPATH=/home/arjen/projecten/javacc2.1/bin/lib/JavaCC.zip

NEWARGS=""

for arg in $@ ;
do
    NEWARGS="${NEWARGS} $arg"
done

java -cp ${CLASSPATH} org.javacc.parser.Main ${NEWARGS}
