#!/bin/sh
#
# Launch JavaCC from bash on Windows
#
# Copyright (C) 1998-2000 Metamata, Inc.

export CLASSPATH=/home/arjen/projecten/Navajo/lib/javacc.jar

NEWARGS=""

for arg in $@ ;
do
    NEWARGS="${NEWARGS} $arg"
done

java org.javacc.jjtree.Main ${NEWARGS}
