/* Generated By:JJTree&JavaCC: Do not edit this line. TMLParserConstants.java */
package com.dexels.navajo.parser;

public interface TMLParserConstants {

  int EOF = 0;
  int AND = 6;
  int OR = 7;
  int NOT = 8;
  int EQUALS = 9;
  int NOT_EQUALS = 10;
  int TRUE = 11;
  int FALSE = 12;
  int TODAY = 13;
  int NAME_OPTION = 14;
  int VALUE_OPTION = 15;
  int BEGIN_LIST = 16;
  int END_LIST = 17;
  int LIST_SEPARATOR = 18;
  int ADD = 19;
  int MUL = 20;
  int MIN = 21;
  int DIV = 22;
  int MOD = 23;
  int SARTRE = 24;
  int INTEGER_LITERAL = 25;
  int DATE_PATTERN = 26;
  int FLOAT_LITERAL = 27;
  int TML_IDENTIFIER = 28;
  int EXISTS_TML_IDENTIFIER = 29;
  int REGULAREXPRESSION = 30;
  int REGULAR1 = 31;
  int REGULAR2 = 32;
  int IDENTIFIER = 33;
  int LETTER = 34;
  int DIGIT = 35;
  int NORMAL_IDENTIFIER = 36;
  int STRING_LITERAL = 37;
  int EXPRESSION_LITERAL = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AND\"",
    "\"OR\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"true\"",
    "\"false\"",
    "\"TODAY\"",
    "\"name\"",
    "\"value\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "<SARTRE>",
    "<INTEGER_LITERAL>",
    "<DATE_PATTERN>",
    "<FLOAT_LITERAL>",
    "<TML_IDENTIFIER>",
    "<EXISTS_TML_IDENTIFIER>",
    "<REGULAREXPRESSION>",
    "<REGULAR1>",
    "<REGULAR2>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NORMAL_IDENTIFIER>",
    "<STRING_LITERAL>",
    "<EXPRESSION_LITERAL>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\":\"",
    "\"]\"",
    "\".\"",
  };

}
