/* Generated By:JJTree: Do not edit this line. TMLParserTreeConstants.java */

package com.dexels.navajo.parser;

public interface TMLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTLISTNODE = 1;
  public int JJTORNODE = 2;
  public int JJTANDNODE = 3;
  public int JJTEQNODE = 4;
  public int JJTNENODE = 5;
  public int JJTLTNODE = 6;
  public int JJTGTNODE = 7;
  public int JJTLENODE = 8;
  public int JJTGENODE = 9;
  public int JJTADDNODE = 10;
  public int JJTSUBTRACTNODE = 11;
  public int JJTMULNODE = 12;
  public int JJTDIVNODE = 13;
  public int JJTMODNODE = 14;
  public int JJTNEGATIVENODE = 15;
  public int JJTNOTNODE = 16;
  public int JJTNULLNODE = 17;
  public int JJTTODAYNODE = 18;
  public int JJTTRUENODE = 19;
  public int JJTFALSENODE = 20;
  public int JJTDATEPATTERNNODE = 21;
  public int JJTFORALLNODE = 22;
  public int JJTFUNCTIONNODE = 23;
  public int JJTFLOATCONSTANTNODE = 24;
  public int JJTINTEGERCONSTANTNODE = 25;
  public int JJTSTRINGCONSTANTNODE = 26;
  public int JJTEXPRESIONLITERALNODE = 27;
  public int JJTTMLNODE = 28;
  public int JJTMAPPABLENODE = 29;


  public String[] jjtNodeName = {
    "void",
    "ListNode",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NegativeNode",
    "NotNode",
    "NullNode",
    "TodayNode",
    "TrueNode",
    "FalseNode",
    "DatePatternNode",
    "ForAllNode",
    "FunctionNode",
    "FloatConstantNode",
    "IntegerConstantNode",
    "StringConstantNode",
    "ExpresionLiteralNode",
    "TmlNode",
    "MappableNode",
  };
}
