/* Generated By:JJTree&JavaCC: Do not edit this line. ASTExpresionLiteralNode.java */

package com.dexels.navajo.parser.compiled;

import java.util.List;

import com.dexels.navajo.expression.api.ContextExpression;
import com.dexels.navajo.parser.compiled.api.ExpressionCache;
import com.dexels.navajo.parser.compiled.api.ParseMode;

public final class ASTExpressionLiteralNode extends SimpleNode {

    String val;

    public ASTExpressionLiteralNode(int id) {
        super(id);
    }


	@Override
	public ContextExpression interpretToLambda(List<String> problems, String expression, ParseMode mode) {
		// TODO is this ok?!
        String value = val.substring(1, val.length() - 1);
        return ExpressionCache.getInstance().parse(problems,value,mode);

	}
}
