/* Generated By:JJTree: Do not edit this line. ASTKeyValueNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dexels.navajo.parser.compiled;

import java.util.List;

import com.dexels.navajo.parser.compiled.api.ContextExpression;

public
class ASTKeyValueNode extends SimpleNode {
  public ASTKeyValueNode(int id) {
    super(id);
  }

  public ASTKeyValueNode(CompiledParser p, int id) {
    super(id);
  }

@Override
public ContextExpression interpretToLambda(List<String> problems, String originalExpression) {
	// TODO Auto-generated method stub
	return null;
}

}
/* JavaCC - OriginalChecksum=52c601dbc6b20940070dc38767537d98 (do not edit this line) */
