/* Generated By:JJTree&JavaCC: Do not edit this line. ASTLENode.java */
package com.dexels.navajo.parser.compiled;


final class ASTLENode extends ComparisonNode {
    
	ASTLENode(int id) {
        super(id);
    }

	protected ComparisonOperator getComparisonOperator()
	{
		return ComparisonNode.ComparisonOperator.LE;
	}
}
