/* Generated By:JJTree: Do not edit this line. ASTTransformerNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.dexels.navajo.parser.compiled;

import java.util.List;
import java.util.function.Function;

import com.dexels.immutable.api.ImmutableMessage;
import com.dexels.navajo.parser.compiled.api.ContextExpression;

public class ASTTransformerNode extends SimpleNode {

	public int args = 0;
	public String transformerName;
  public ASTTransformerNode(int id) {
    super(id);
  }

@Override
public ContextExpression interpretToLambda(List<String> problems, String originalExpression) {
	// TODO do something prettier
	throw new RuntimeException("Can't interpret a transformer");
}

public Function<ImmutableMessage,ImmutableMessage> evaluateTransformer() {
	
	for (int i = 0; i < jjtGetNumChildren(); i++) {
		Node node = jjtGetChild(i);
		
		
	}
	return null;
	
}

}
/* JavaCC - OriginalChecksum=1d2eb60a4b53e6f73d69612ad626466b (do not edit this line) */
