/* Generated By:JJTree&JavaCC: Do not edit this line. TMLParserConstants.java */
package com.dexels.navajo.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int EQUALS = 8;
  /** RegularExpression Id. */
  int NOT_EQUALS = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int TODAY = 12;
  /** RegularExpression Id. */
  int NAME_OPTION = 13;
  /** RegularExpression Id. */
  int VALUE_OPTION = 14;
  /** RegularExpression Id. */
  int BEGIN_LIST = 15;
  /** RegularExpression Id. */
  int END_LIST = 16;
  /** RegularExpression Id. */
  int LIST_SEPARATOR = 17;
  /** RegularExpression Id. */
  int ADD = 18;
  /** RegularExpression Id. */
  int MUL = 19;
  /** RegularExpression Id. */
  int MIN = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int MOD = 22;
  /** RegularExpression Id. */
  int NULL = 23;
  /** RegularExpression Id. */
  int SARTRE = 24;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 25;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 26;
  /** RegularExpression Id. */
  int TML_IDENTIFIER = 27;
  /** RegularExpression Id. */
  int EXISTS_TML_IDENTIFIER = 28;
  /** RegularExpression Id. */
  int REGULAREXPRESSION = 29;
  /** RegularExpression Id. */
  int PARENT_MSG = 30;
  /** RegularExpression Id. */
  int REGULAR1 = 31;
  /** RegularExpression Id. */
  int REGULAR2 = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;
  /** RegularExpression Id. */
  int NORMAL_IDENTIFIER = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int EXPRESSION_LITERAL = 38;
  /** RegularExpression Id. */
  int TIPI_IDENTIFIER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AND\"",
    "\"OR\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"true\"",
    "\"false\"",
    "\"TODAY\"",
    "\":name\"",
    "\":value\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"null\"",
    "<SARTRE>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<TML_IDENTIFIER>",
    "<EXISTS_TML_IDENTIFIER>",
    "<REGULAREXPRESSION>",
    "\"../\"",
    "<REGULAR1>",
    "<REGULAR2>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NORMAL_IDENTIFIER>",
    "<STRING_LITERAL>",
    "<EXPRESSION_LITERAL>",
    "<TIPI_IDENTIFIER>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\"]\"",
    "\".\"",
  };

}
