/*
 * generated by Xtext
 */
package com.dexels.navajo.dsl.tsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.dexels.navajo.dsl.tsl.ui.highlighting.TslHighlightingConfiguration;
import com.dexels.navajo.dsl.tsl.ui.highlighting.TslLexicalHighlightingMapper;
import com.dexels.navajo.dsl.tsl.ui.highlighting.TslSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TslUiModule extends
		com.dexels.navajo.dsl.tsl.ui.AbstractTslUiModule {
	public TslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
//		NavajoScriptPluginPlugin.getDefault().addNavajoActivityListener(new INavajoActivityListener(){
//
//			@Override
//			public void navajoResponse(Navajo n, String scriptName) {
//				System.err.println("NAVAJO CALLLLLLLLLED: "+scriptName);
//				Injector ii = TslActivator.getInstance().getInjector("com.dexels.navajo.dsl.tsl.Tsl");
//				INavajoContextProvider icp2 = ii.getInstance(INavajoContextProvider.class);
//				icp2.setInputNavajo(n);
//			}});
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return TslSemanticHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindSemanticConfig() {
		return TslHighlightingConfiguration.class;
	}
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return TslLexicalHighlightingMapper.class ;
	}

//	  @Override
//	  public Class<? extends ISemanticModelTransformer> 
//	  	 bindISemanticModelTransformer() {
//	    return TslTransformer.class;
//	  }
	
}
