/*
* generated by Xtext
*/

package com.dexels.navajo.dsl.tsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import com.dexels.navajo.dsl.expression.services.NavajoExpressionGrammarAccess;

@Singleton
public class TslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TmlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Tml");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNavascriptKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cTmlAction_1 = (Action)cGroup.eContents().get(1);
		private final Assignment cAttributesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttributesPossibleExpressionParserRuleCall_2_0 = (RuleCall)cAttributesAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Alternatives cAlternatives_3_0_1 = (Alternatives)cGroup_3_0.eContents().get(1);
		private final Assignment cChildrenAssignment_3_0_1_0 = (Assignment)cAlternatives_3_0_1.eContents().get(0);
		private final RuleCall cChildrenMessageParserRuleCall_3_0_1_0_0 = (RuleCall)cChildrenAssignment_3_0_1_0.eContents().get(0);
		private final Assignment cChildrenAssignment_3_0_1_1 = (Assignment)cAlternatives_3_0_1.eContents().get(1);
		private final RuleCall cChildrenMapParserRuleCall_3_0_1_1_0 = (RuleCall)cChildrenAssignment_3_0_1_1.eContents().get(0);
		private final Keyword cNavascriptKeyword_3_0_2 = (Keyword)cGroup_3_0.eContents().get(2);
		private final Keyword cSolidusGreaterThanSignKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		
		////com.dexels.navajo.dsl.expression/src-gen/com/dexels.navajo/dsl/expression/NavajoExpression.ecore"
		////generate tsl "http://www.dexels.com/navajo/dsl/tsl/NavajoTsl"
		//Tml:
		//	"<navascript" {Tml} attributes+=PossibleExpression* (">" (children+=Message | children+=Map)* "</navascript>" | "/>");
		public ParserRule getRule() { return rule; }

		//"<navascript" {Tml} attributes+=PossibleExpression* (">" (children+=Message | children+=Map)* "</navascript>" | "/>")
		public Group getGroup() { return cGroup; }

		//"<navascript"
		public Keyword getNavascriptKeyword_0() { return cNavascriptKeyword_0; }

		//{Tml}
		public Action getTmlAction_1() { return cTmlAction_1; }

		//attributes+=PossibleExpression*
		public Assignment getAttributesAssignment_2() { return cAttributesAssignment_2; }

		//PossibleExpression
		public RuleCall getAttributesPossibleExpressionParserRuleCall_2_0() { return cAttributesPossibleExpressionParserRuleCall_2_0; }

		//">" (children+=Message | children+=Map)* "</navascript>" | "/>"
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//">" (children+=Message | children+=Map)* "</navascript>"
		public Group getGroup_3_0() { return cGroup_3_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_3_0_0() { return cGreaterThanSignKeyword_3_0_0; }

		//(children+=Message | children+=Map)*
		public Alternatives getAlternatives_3_0_1() { return cAlternatives_3_0_1; }

		//children+=Message
		public Assignment getChildrenAssignment_3_0_1_0() { return cChildrenAssignment_3_0_1_0; }

		//Message
		public RuleCall getChildrenMessageParserRuleCall_3_0_1_0_0() { return cChildrenMessageParserRuleCall_3_0_1_0_0; }

		//children+=Map
		public Assignment getChildrenAssignment_3_0_1_1() { return cChildrenAssignment_3_0_1_1; }

		//Map
		public RuleCall getChildrenMapParserRuleCall_3_0_1_1_0() { return cChildrenMapParserRuleCall_3_0_1_1_0; }

		//"</navascript>"
		public Keyword getNavascriptKeyword_3_0_2() { return cNavascriptKeyword_3_0_2; }

		//"/>"
		public Keyword getSolidusGreaterThanSignKeyword_3_1() { return cSolidusGreaterThanSignKeyword_3_1; }
	}

	public class PossibleExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PossibleExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeyIDTerminalRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cQuotationMarkEqualsSignKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cExpressionValueAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cExpressionValueTopLevelParserRuleCall_2_0_1_0 = (RuleCall)cExpressionValueAssignment_2_0_1.eContents().get(0);
		private final Keyword cSemicolonQuotationMarkKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cValueAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cValueATTRIBUTESTRINGTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		
		//PossibleExpression:
		//	key=ID "=" ("\"=" expressionValue=TopLevel ";\"" | value=ATTRIBUTESTRING);
		public ParserRule getRule() { return rule; }

		//key=ID "=" ("\"=" expressionValue=TopLevel ";\"" | value=ATTRIBUTESTRING)
		public Group getGroup() { return cGroup; }

		//key=ID
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }

		//ID
		public RuleCall getKeyIDTerminalRuleCall_0_0() { return cKeyIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//"\"=" expressionValue=TopLevel ";\"" | value=ATTRIBUTESTRING
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//"\"=" expressionValue=TopLevel ";\""
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"\"="
		public Keyword getQuotationMarkEqualsSignKeyword_2_0_0() { return cQuotationMarkEqualsSignKeyword_2_0_0; }

		//expressionValue=TopLevel
		public Assignment getExpressionValueAssignment_2_0_1() { return cExpressionValueAssignment_2_0_1; }

		//TopLevel
		public RuleCall getExpressionValueTopLevelParserRuleCall_2_0_1_0() { return cExpressionValueTopLevelParserRuleCall_2_0_1_0; }

		//";\""
		public Keyword getSemicolonQuotationMarkKeyword_2_0_2() { return cSemicolonQuotationMarkKeyword_2_0_2; }

		//value=ATTRIBUTESTRING
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }

		//ATTRIBUTESTRING
		public RuleCall getValueATTRIBUTESTRINGTerminalRuleCall_2_1_0() { return cValueATTRIBUTESTRINGTerminalRuleCall_2_1_0; }
	}

	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMessageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cMessageAction_1 = (Action)cGroup.eContents().get(1);
		private final Assignment cAttributesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttributesPossibleExpressionParserRuleCall_2_0 = (RuleCall)cAttributesAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Alternatives cAlternatives_3_0_1 = (Alternatives)cGroup_3_0.eContents().get(1);
		private final Assignment cChildrenAssignment_3_0_1_0 = (Assignment)cAlternatives_3_0_1.eContents().get(0);
		private final RuleCall cChildrenMessageParserRuleCall_3_0_1_0_0 = (RuleCall)cChildrenAssignment_3_0_1_0.eContents().get(0);
		private final Assignment cChildrenAssignment_3_0_1_1 = (Assignment)cAlternatives_3_0_1.eContents().get(1);
		private final RuleCall cChildrenPropertyParserRuleCall_3_0_1_1_0 = (RuleCall)cChildrenAssignment_3_0_1_1.eContents().get(0);
		private final Assignment cChildrenAssignment_3_0_1_2 = (Assignment)cAlternatives_3_0_1.eContents().get(2);
		private final RuleCall cChildrenMapParserRuleCall_3_0_1_2_0 = (RuleCall)cChildrenAssignment_3_0_1_2.eContents().get(0);
		private final Keyword cMessageKeyword_3_0_2 = (Keyword)cGroup_3_0.eContents().get(2);
		private final Keyword cSolidusGreaterThanSignKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		
		//Message:
		//	"<message" {Message} attributes+=PossibleExpression* (">" (children+=Message | children+=Property | children+=Map)*
		//	"</message>" | "/>");
		public ParserRule getRule() { return rule; }

		//"<message" {Message} attributes+=PossibleExpression* (">" (children+=Message | children+=Property | children+=Map)*
		//"</message>" | "/>")
		public Group getGroup() { return cGroup; }

		//"<message"
		public Keyword getMessageKeyword_0() { return cMessageKeyword_0; }

		//{Message}
		public Action getMessageAction_1() { return cMessageAction_1; }

		//attributes+=PossibleExpression*
		public Assignment getAttributesAssignment_2() { return cAttributesAssignment_2; }

		//PossibleExpression
		public RuleCall getAttributesPossibleExpressionParserRuleCall_2_0() { return cAttributesPossibleExpressionParserRuleCall_2_0; }

		//">" (children+=Message | children+=Property | children+=Map)* "</message>" | "/>"
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//">" (children+=Message | children+=Property | children+=Map)* "</message>"
		public Group getGroup_3_0() { return cGroup_3_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_3_0_0() { return cGreaterThanSignKeyword_3_0_0; }

		//(children+=Message | children+=Property | children+=Map)*
		public Alternatives getAlternatives_3_0_1() { return cAlternatives_3_0_1; }

		//children+=Message
		public Assignment getChildrenAssignment_3_0_1_0() { return cChildrenAssignment_3_0_1_0; }

		//Message
		public RuleCall getChildrenMessageParserRuleCall_3_0_1_0_0() { return cChildrenMessageParserRuleCall_3_0_1_0_0; }

		//children+=Property
		public Assignment getChildrenAssignment_3_0_1_1() { return cChildrenAssignment_3_0_1_1; }

		//Property
		public RuleCall getChildrenPropertyParserRuleCall_3_0_1_1_0() { return cChildrenPropertyParserRuleCall_3_0_1_1_0; }

		//children+=Map
		public Assignment getChildrenAssignment_3_0_1_2() { return cChildrenAssignment_3_0_1_2; }

		//Map
		public RuleCall getChildrenMapParserRuleCall_3_0_1_2_0() { return cChildrenMapParserRuleCall_3_0_1_2_0; }

		//"</message>"
		public Keyword getMessageKeyword_3_0_2() { return cMessageKeyword_3_0_2; }

		//"/>"
		public Keyword getSolidusGreaterThanSignKeyword_3_1() { return cSolidusGreaterThanSignKeyword_3_1; }
	}

	public class MapElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Map");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMapAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMapKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMapNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMapNameIDTerminalRuleCall_2_0 = (RuleCall)cMapNameAssignment_2.eContents().get(0);
		private final Assignment cAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttributesPossibleExpressionParserRuleCall_3_0 = (RuleCall)cAttributesAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Keyword cSolidusGreaterThanSignKeyword_4_0 = (Keyword)cAlternatives_4.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Alternatives cAlternatives_4_1_1 = (Alternatives)cGroup_4_1.eContents().get(1);
		private final Assignment cChildrenAssignment_4_1_1_0 = (Assignment)cAlternatives_4_1_1.eContents().get(0);
		private final RuleCall cChildrenMessageParserRuleCall_4_1_1_0_0 = (RuleCall)cChildrenAssignment_4_1_1_0.eContents().get(0);
		private final Assignment cChildrenAssignment_4_1_1_1 = (Assignment)cAlternatives_4_1_1.eContents().get(1);
		private final RuleCall cChildrenPropertyParserRuleCall_4_1_1_1_0 = (RuleCall)cChildrenAssignment_4_1_1_1.eContents().get(0);
		private final Assignment cChildrenAssignment_4_1_1_2 = (Assignment)cAlternatives_4_1_1.eContents().get(2);
		private final RuleCall cChildrenMapParserRuleCall_4_1_1_2_0 = (RuleCall)cChildrenAssignment_4_1_1_2.eContents().get(0);
		private final Keyword cMapKeyword_4_1_2 = (Keyword)cGroup_4_1.eContents().get(2);
		private final Assignment cMapClosingNameAssignment_4_1_3 = (Assignment)cGroup_4_1.eContents().get(3);
		private final RuleCall cMapClosingNameIDTerminalRuleCall_4_1_3_0 = (RuleCall)cMapClosingNameAssignment_4_1_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_4_1_4 = (Keyword)cGroup_4_1.eContents().get(4);
		
		//Map:
		//	{Map} "<map." mapName=ID attributes+=PossibleExpression ("/>" | ">" (children+=Message | children+=Property |
		//	children+=Map)* "</map." mapClosingName=ID ">");
		public ParserRule getRule() { return rule; }

		//{Map} "<map." mapName=ID attributes+=PossibleExpression ("/>" | ">" (children+=Message | children+=Property |
		//children+=Map)* "</map." mapClosingName=ID ">")
		public Group getGroup() { return cGroup; }

		//{Map}
		public Action getMapAction_0() { return cMapAction_0; }

		//"<map."
		public Keyword getMapKeyword_1() { return cMapKeyword_1; }

		//mapName=ID
		public Assignment getMapNameAssignment_2() { return cMapNameAssignment_2; }

		//ID
		public RuleCall getMapNameIDTerminalRuleCall_2_0() { return cMapNameIDTerminalRuleCall_2_0; }

		//attributes+=PossibleExpression
		public Assignment getAttributesAssignment_3() { return cAttributesAssignment_3; }

		//PossibleExpression
		public RuleCall getAttributesPossibleExpressionParserRuleCall_3_0() { return cAttributesPossibleExpressionParserRuleCall_3_0; }

		//"/>" | ">" (children+=Message | children+=Property | children+=Map)* "</map." mapClosingName=ID ">"
		public Alternatives getAlternatives_4() { return cAlternatives_4; }

		//"/>"
		public Keyword getSolidusGreaterThanSignKeyword_4_0() { return cSolidusGreaterThanSignKeyword_4_0; }

		//">" (children+=Message | children+=Property | children+=Map)* "</map." mapClosingName=ID ">"
		public Group getGroup_4_1() { return cGroup_4_1; }

		//">"
		public Keyword getGreaterThanSignKeyword_4_1_0() { return cGreaterThanSignKeyword_4_1_0; }

		//(children+=Message | children+=Property | children+=Map)*
		public Alternatives getAlternatives_4_1_1() { return cAlternatives_4_1_1; }

		//children+=Message
		public Assignment getChildrenAssignment_4_1_1_0() { return cChildrenAssignment_4_1_1_0; }

		//Message
		public RuleCall getChildrenMessageParserRuleCall_4_1_1_0_0() { return cChildrenMessageParserRuleCall_4_1_1_0_0; }

		//children+=Property
		public Assignment getChildrenAssignment_4_1_1_1() { return cChildrenAssignment_4_1_1_1; }

		//Property
		public RuleCall getChildrenPropertyParserRuleCall_4_1_1_1_0() { return cChildrenPropertyParserRuleCall_4_1_1_1_0; }

		//children+=Map
		public Assignment getChildrenAssignment_4_1_1_2() { return cChildrenAssignment_4_1_1_2; }

		//Map
		public RuleCall getChildrenMapParserRuleCall_4_1_1_2_0() { return cChildrenMapParserRuleCall_4_1_1_2_0; }

		//"</map."
		public Keyword getMapKeyword_4_1_2() { return cMapKeyword_4_1_2; }

		//mapClosingName=ID
		public Assignment getMapClosingNameAssignment_4_1_3() { return cMapClosingNameAssignment_4_1_3; }

		//ID
		public RuleCall getMapClosingNameIDTerminalRuleCall_4_1_3_0() { return cMapClosingNameIDTerminalRuleCall_4_1_3_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_4_1_4() { return cGreaterThanSignKeyword_4_1_4; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Action cPropertyAction_1 = (Action)cGroup.eContents().get(1);
		private final Assignment cAttributesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttributesPossibleExpressionParserRuleCall_2_0 = (RuleCall)cAttributesAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cSolidusGreaterThanSignKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cExpressionValueAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cExpressionValueExpressionTagParserRuleCall_3_1_1_0 = (RuleCall)cExpressionValueAssignment_3_1_1.eContents().get(0);
		private final Keyword cPropertyKeyword_3_1_2 = (Keyword)cGroup_3_1.eContents().get(2);
		
		//// doesn't seem to work. All are optional
		////Modifier: static?='static'? & final?='final'? & visibility=Visibility;
		//// ToDo Add ALL types!
		//// this fails. All these possibilities will be tokens/keywords, so it will break other stuff.
		////PropertyTypes: STRING_PROPERTY='string' | INTEGER_PROPERTY='integer' | LONG_PROPERTY='long' | DATE_PROPERTY = "date" | FLOAT_PROPERTY = "float";
		////MessageTypes: MSG_TYPE_SIMPLE='simple' |  MSG_TYPE_ARRAY = "array" | MSG_TYPE_TABLE = "table";
		////MessageModes: MSG_MODE = "mode" | MSG_MODE_LAZY = "lazy" | MSG_MODE_IGNORE = "ignore" | MSG_MODE_OVERWRITE = "overwrite";
		//// The direction 'inout' has been deprecated, so I've left that one out.
		////PropertyDirection: DIR_IN = "in" | DIR_OUT = "out";
		//// '1' this makes 1 a keyword
		////PropertyCardinalities: CARDINALITY_SINGLE = "1" | CARDINALITY_MULTIPLE = "+";
		//Property:
		//	"<property" {Property} attributes+=PossibleExpression* ("/>" | ">" expressionValue=ExpressionTag? "</property>");
		public ParserRule getRule() { return rule; }

		//"<property" {Property} attributes+=PossibleExpression* ("/>" | ">" expressionValue=ExpressionTag? "</property>")
		public Group getGroup() { return cGroup; }

		//"<property"
		public Keyword getPropertyKeyword_0() { return cPropertyKeyword_0; }

		//{Property}
		public Action getPropertyAction_1() { return cPropertyAction_1; }

		//attributes+=PossibleExpression*
		public Assignment getAttributesAssignment_2() { return cAttributesAssignment_2; }

		//PossibleExpression
		public RuleCall getAttributesPossibleExpressionParserRuleCall_2_0() { return cAttributesPossibleExpressionParserRuleCall_2_0; }

		//"/>" | ">" expressionValue=ExpressionTag? "</property>"
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//"/>"
		public Keyword getSolidusGreaterThanSignKeyword_3_0() { return cSolidusGreaterThanSignKeyword_3_0; }

		//">" expressionValue=ExpressionTag? "</property>"
		public Group getGroup_3_1() { return cGroup_3_1; }

		//">"
		public Keyword getGreaterThanSignKeyword_3_1_0() { return cGreaterThanSignKeyword_3_1_0; }

		//expressionValue=ExpressionTag?
		public Assignment getExpressionValueAssignment_3_1_1() { return cExpressionValueAssignment_3_1_1; }

		//ExpressionTag
		public RuleCall getExpressionValueExpressionTagParserRuleCall_3_1_1_0() { return cExpressionValueExpressionTagParserRuleCall_3_1_1_0; }

		//"</property>"
		public Keyword getPropertyKeyword_3_1_2() { return cPropertyKeyword_3_1_2; }
	}

	public class ExpressionTagElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpressionTag");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpressionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueTopLevelParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExpressionTag:
		//	"<expression>" value=TopLevel "</expression>";
		public ParserRule getRule() { return rule; }

		//"<expression>" value=TopLevel "</expression>"
		public Group getGroup() { return cGroup; }

		//"<expression>"
		public Keyword getExpressionKeyword_0() { return cExpressionKeyword_0; }

		//value=TopLevel
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//TopLevel
		public RuleCall getValueTopLevelParserRuleCall_1_0() { return cValueTopLevelParserRuleCall_1_0; }

		//"</expression>"
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
	}
	
	
	private TmlElements pTml;
	private TerminalRule tATTRIBUTESTRING;
	private PossibleExpressionElements pPossibleExpression;
	private MessageElements pMessage;
	private MapElements pMap;
	private PropertyElements pProperty;
	private ExpressionTagElements pExpressionTag;
	
	private final GrammarProvider grammarProvider;

	private NavajoExpressionGrammarAccess gaNavajoExpression;

	@Inject
	public TslGrammarAccess(GrammarProvider grammarProvider,
		NavajoExpressionGrammarAccess gaNavajoExpression) {
		this.grammarProvider = grammarProvider;
		this.gaNavajoExpression = gaNavajoExpression;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public NavajoExpressionGrammarAccess getNavajoExpressionGrammarAccess() {
		return gaNavajoExpression;
	}

	
	////com.dexels.navajo.dsl.expression/src-gen/com/dexels.navajo/dsl/expression/NavajoExpression.ecore"
	////generate tsl "http://www.dexels.com/navajo/dsl/tsl/NavajoTsl"
	//Tml:
	//	"<navascript" {Tml} attributes+=PossibleExpression* (">" (children+=Message | children+=Map)* "</navascript>" | "/>");
	public TmlElements getTmlAccess() {
		return (pTml != null) ? pTml : (pTml = new TmlElements());
	}
	
	public ParserRule getTmlRule() {
		return getTmlAccess().getRule();
	}

	////terminal QUOT: '"';	
	//terminal ATTRIBUTESTRING:
	//	"\"" !"=" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* !";" "\"" | "\"\"" | "\"" !"\""
	//	"\"";
	public TerminalRule getATTRIBUTESTRINGRule() {
		return (tATTRIBUTESTRING != null) ? tATTRIBUTESTRING : (tATTRIBUTESTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ATTRIBUTESTRING"));
	} 

	//PossibleExpression:
	//	key=ID "=" ("\"=" expressionValue=TopLevel ";\"" | value=ATTRIBUTESTRING);
	public PossibleExpressionElements getPossibleExpressionAccess() {
		return (pPossibleExpression != null) ? pPossibleExpression : (pPossibleExpression = new PossibleExpressionElements());
	}
	
	public ParserRule getPossibleExpressionRule() {
		return getPossibleExpressionAccess().getRule();
	}

	//Message:
	//	"<message" {Message} attributes+=PossibleExpression* (">" (children+=Message | children+=Property | children+=Map)*
	//	"</message>" | "/>");
	public MessageElements getMessageAccess() {
		return (pMessage != null) ? pMessage : (pMessage = new MessageElements());
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}

	//Map:
	//	{Map} "<map." mapName=ID attributes+=PossibleExpression ("/>" | ">" (children+=Message | children+=Property |
	//	children+=Map)* "</map." mapClosingName=ID ">");
	public MapElements getMapAccess() {
		return (pMap != null) ? pMap : (pMap = new MapElements());
	}
	
	public ParserRule getMapRule() {
		return getMapAccess().getRule();
	}

	//// doesn't seem to work. All are optional
	////Modifier: static?='static'? & final?='final'? & visibility=Visibility;
	//// ToDo Add ALL types!
	//// this fails. All these possibilities will be tokens/keywords, so it will break other stuff.
	////PropertyTypes: STRING_PROPERTY='string' | INTEGER_PROPERTY='integer' | LONG_PROPERTY='long' | DATE_PROPERTY = "date" | FLOAT_PROPERTY = "float";
	////MessageTypes: MSG_TYPE_SIMPLE='simple' |  MSG_TYPE_ARRAY = "array" | MSG_TYPE_TABLE = "table";
	////MessageModes: MSG_MODE = "mode" | MSG_MODE_LAZY = "lazy" | MSG_MODE_IGNORE = "ignore" | MSG_MODE_OVERWRITE = "overwrite";
	//// The direction 'inout' has been deprecated, so I've left that one out.
	////PropertyDirection: DIR_IN = "in" | DIR_OUT = "out";
	//// '1' this makes 1 a keyword
	////PropertyCardinalities: CARDINALITY_SINGLE = "1" | CARDINALITY_MULTIPLE = "+";
	//Property:
	//	"<property" {Property} attributes+=PossibleExpression* ("/>" | ">" expressionValue=ExpressionTag? "</property>");
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//ExpressionTag:
	//	"<expression>" value=TopLevel "</expression>";
	public ExpressionTagElements getExpressionTagAccess() {
		return (pExpressionTag != null) ? pExpressionTag : (pExpressionTag = new ExpressionTagElements());
	}
	
	public ParserRule getExpressionTagRule() {
		return getExpressionTagAccess().getRule();
	}

	////import "classpath:/com/dexels/navajo/dsl/expression/Navajo.ecore"
	////import "file:///Users/frank/Documents/workspace-xtext/com.dexels.navajo.dsl.expression/src/com/dexels/navajo/dsl/expression/Navajo.ecore" as ncore
	////import "http://www.dexels.com/navajo/dsl/expression/NavajoCore" as ncore
	////generate navajoExpression "http://www.dexels.com/navajo/dsl/expression/NavajoExpression"
	////terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	//TopLevel: //	 toplevelExpression =OrExpression
	//	{TopLevel} toplevelExpression=OrExpression;
	public NavajoExpressionGrammarAccess.TopLevelElements getTopLevelAccess() {
		return gaNavajoExpression.getTopLevelAccess();
	}
	
	public ParserRule getTopLevelRule() {
		return getTopLevelAccess().getRule();
	}

	//terminal INT:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaNavajoExpression.getINTRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaNavajoExpression.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaNavajoExpression.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaNavajoExpression.getWSRule();
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaNavajoExpression.getIDRule();
	} 

	//terminal LITERALSTRING:
	//	"\'" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getLITERALSTRINGRule() {
		return gaNavajoExpression.getLITERALSTRINGRule();
	} 

	//// skipped url, image, points, datepattern, password
	////terminal PATH_ELEMENT: ('.'|'..'|("a".. "z"| "A" .. "Z"|"_")("a".. "z"| "A" .. "Z"|"0" .. "9"|"_")*);
	//PathElement returns ecore::EString:
	//	ID | "." | "..";
	public NavajoExpressionGrammarAccess.PathElementElements getPathElementAccess() {
		return gaNavajoExpression.getPathElementAccess();
	}
	
	public ParserRule getPathElementRule() {
		return getPathElementAccess().getRule();
	}

	//PathSequence returns ecore::EString:
	//	"[" "/"? PathElement ("/" PathElement)* "]";
	public NavajoExpressionGrammarAccess.PathSequenceElements getPathSequenceAccess() {
		return gaNavajoExpression.getPathSequenceAccess();
	}
	
	public ParserRule getPathSequenceRule() {
		return getPathSequenceAccess().getRule();
	}

	//TmlExpression returns ecore::EString:
	//	PathSequence;
	public NavajoExpressionGrammarAccess.TmlExpressionElements getTmlExpressionAccess() {
		return gaNavajoExpression.getTmlExpressionAccess();
	}
	
	public ParserRule getTmlExpressionRule() {
		return getTmlExpressionAccess().getRule();
	}

	//ExistsTmlExpression returns ecore::EString:
	//	"?" TmlExpression;
	public NavajoExpressionGrammarAccess.ExistsTmlExpressionElements getExistsTmlExpressionAccess() {
		return gaNavajoExpression.getExistsTmlExpressionAccess();
	}
	
	public ParserRule getExistsTmlExpressionRule() {
		return getExistsTmlExpressionAccess().getRule();
	}

	//OrExpression returns Expression:
	//	{Expression} parameters+=AndExpression (operations+="OR" parameters+=AndExpression)*;
	public NavajoExpressionGrammarAccess.OrExpressionElements getOrExpressionAccess() {
		return gaNavajoExpression.getOrExpressionAccess();
	}
	
	public ParserRule getOrExpressionRule() {
		return getOrExpressionAccess().getRule();
	}

	//AndExpression returns Expression:
	//	{Expression} parameters+=EqualityExpression (operations+="AND" parameters+=EqualityExpression)*;
	public NavajoExpressionGrammarAccess.AndExpressionElements getAndExpressionAccess() {
		return gaNavajoExpression.getAndExpressionAccess();
	}
	
	public ParserRule getAndExpressionRule() {
		return getAndExpressionAccess().getRule();
	}

	//EqualityExpression returns Expression:
	//	{Expression} parameters+=AdditiveExpression (operations+="==" parameters+=AdditiveExpression | operations+="!="
	//	parameters+=AdditiveExpression)?;
	public NavajoExpressionGrammarAccess.EqualityExpressionElements getEqualityExpressionAccess() {
		return gaNavajoExpression.getEqualityExpressionAccess();
	}
	
	public ParserRule getEqualityExpressionRule() {
		return getEqualityExpressionAccess().getRule();
	}

	//// Skipped for now. Trouble with overloaded '<' stuff  
	////RelationalExpression returns Expression: 
	////   {Expression} operands+=AdditiveExpression ((op='&lt;' operands+=AdditiveExpression)|(op='&gt;' operands+=AdditiveExpression)|(op='&lt;=' operands+=AdditiveExpression)|(op='&gt;=' operands+=AdditiveExpression))?
	////    ;
	//AdditiveExpression returns Expression:
	//	{Expression} parameters+=MultiplicativeExpression ("+" parameters+=MultiplicativeExpression | "-"
	//	parameters+=MultiplicativeExpression)*;
	public NavajoExpressionGrammarAccess.AdditiveExpressionElements getAdditiveExpressionAccess() {
		return gaNavajoExpression.getAdditiveExpressionAccess();
	}
	
	public ParserRule getAdditiveExpressionRule() {
		return getAdditiveExpressionAccess().getRule();
	}

	//MultiplicativeExpression returns Expression:
	//	{Expression} parameters+=UnaryExpression (operations+="*" parameters+=UnaryExpression | operations+="/"
	//	parameters+=UnaryExpression)*;
	public NavajoExpressionGrammarAccess.MultiplicativeExpressionElements getMultiplicativeExpressionAccess() {
		return gaNavajoExpression.getMultiplicativeExpressionAccess();
	}
	
	public ParserRule getMultiplicativeExpressionRule() {
		return getMultiplicativeExpressionAccess().getRule();
	}

	//UnaryExpression returns Expression:
	//	{Expression} operations+="!" parameters+=PrimaryExpression | PrimaryExpression;
	public NavajoExpressionGrammarAccess.UnaryExpressionElements getUnaryExpressionAccess() {
		return gaNavajoExpression.getUnaryExpressionAccess();
	}
	
	public ParserRule getUnaryExpressionRule() {
		return getUnaryExpressionAccess().getRule();
	}

	//PrimaryExpression returns Expression:
	//	{Expression} parameters+=Literal | "(" parameters+=OrExpression ")";
	public NavajoExpressionGrammarAccess.PrimaryExpressionElements getPrimaryExpressionAccess() {
		return gaNavajoExpression.getPrimaryExpressionAccess();
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}

	////
	////FunctionName:
	////	ID;
	//FunctionCall:
	//	name=ID "(" operands=[FunctionOperands] ")";
	public NavajoExpressionGrammarAccess.FunctionCallElements getFunctionCallAccess() {
		return gaNavajoExpression.getFunctionCallAccess();
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}

	//FunctionOperands:
	//	{FunctionOperands} parameters+=OrExpression? ("," parameters+=OrExpression)*;
	public NavajoExpressionGrammarAccess.FunctionOperandsElements getFunctionOperandsAccess() {
		return gaNavajoExpression.getFunctionOperandsAccess();
	}
	
	public ParserRule getFunctionOperandsRule() {
		return getFunctionOperandsAccess().getRule();
	}

	////Expression returns Expression:
	////	Literal | FunctionCall | FunctionOperands ;
	//Literal returns Expression:
	//	{Expression} valueString=INT // TODO Add float
	//	| {Expression} valueString=LITERALSTRING | {Expression} operations+="FORALL" "(" valueString=LITERALSTRING ","
	//	parameters+=OrExpression ")" | FunctionCall | {Expression} elements+=ExistsTmlExpression | {Expression}
	//	elements+=TmlExpression | {Expression} expressionType="{" parameters+=OrExpression? ("," parameters+=OrExpression)*
	//	"}" | {Expression} elements+="NULL" | {Expression} elements+="TODAY" | {Expression} elements+="TRUE" | {Expression}
	//	elements+="FALSE";
	public NavajoExpressionGrammarAccess.LiteralElements getLiteralAccess() {
		return gaNavajoExpression.getLiteralAccess();
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}
}
